Repository culturecreates/footlight-app, pull requests merged in 2023-10, with the labels that each got.

#636 Feature/issue 596
  src/constants/formFields.js
  src/locales/en/translationEn.json
  src/locales/fr/transalationFr.json
  src/utils/formPayloadHandler.js
Labels: subtasks

#639 feat: added social media links to read only page
  src/locales/en/translationEn.json
  src/locales/fr/transalationFr.json
  src/pages/Dashboard/OrganizationsReadOnly/OrganizationsReadOnly.jsx
  src/pages/Dashboard/PersonReadOnly/PersonReadOnly.jsx
Labels: subtasks

#642 Feature/issue 596
  src/constants/formFields.js
Labels: bug

#643 Feature/issue 596
  src/pages/Dashboard/CreateNewOrganization/CreateNewOrganization.jsx
  src/pages/Dashboard/CreateNewPerson/CreateNewPerson.jsx
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
  src/pages/Dashboard/OrganizationsReadOnly/OrganizationsReadOnly.jsx
  src/pages/Dashboard/PersonReadOnly/PersonReadOnly.jsx
  src/pages/Dashboard/PlaceReadOnly/PlaceReadOnly.jsx
Labels: bug

#650 fix: added include concepts and taxonomy class to get taxonomy
  src/components/TreeSelectOption/treeSelectOption.settings.js
  src/services/taxonomy.js
Labels: bug

#651 fix: image upload fix by removing initial set states
  src/components/ImageCrop/ImageCrop.jsx
Labels: bug

#656 fix: fixed header not showing artsdata details in place read only
  src/pages/Dashboard/PlaceReadOnly/PlaceReadOnly.jsx
Labels: bug

#658 Feature/issue 571 661
  src/components/Modal/QuickCreateOrganization/QuickCreateOrganization.jsx
  src/components/Modal/QuickCreatePerson/QuickCreatePerson.jsx
  src/components/Select/selectOption.settings.js
  src/components/TreeSelectOption/treeSelectOption.settings.js
  src/constants/formFields.js
  src/constants/sourceOptions.js
  src/pages/Dashboard/AddEvent/AddEvent.jsx
  src/pages/Dashboard/AddEvent/addEvent.css
  src/pages/Dashboard/CreateNewOrganization/CreateNewOrganization.jsx
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
  src/pages/Dashboard/EventReadOnly/EventReadOnly.jsx
  src/pages/Dashboard/SearchOrganizations/SearchOrganizations.jsx
  src/pages/Dashboard/SearchPerson/SearchPerson.jsx
  src/pages/Dashboard/SearchPlaces/SearchPlaces.jsx
  src/redux/store.js
  src/services/entities.js
Labels: feature

#661 fix: respective place is removed from the contained in place search dropdown
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
Labels: bug, enhancement

#660 Bugfix/issue 648
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
Labels: bug

#665 feat: added support for derived from
  src/pages/Dashboard/CreateNewOrganization/CreateNewOrganization.jsx
  src/pages/Dashboard/CreateNewPerson/CreateNewPerson.jsx
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
  src/router/index.js
  src/utils/getExternalSourceId.js
Labels: enhancement

#666 fix: added artsdata link to search dropdowns in event edit screens
  src/components/List/SelectionItem/SelectionItem.jsx
  src/components/Select/selectOption.settings.js
  src/components/Tags/ArtsDataLink/artsDataLink.css
  src/components/TreeSelectOption/treeSelectOption.settings.js
  src/pages/Dashboard/OrganizationsReadOnly/OrganizationsReadOnly.jsx
  src/pages/Dashboard/PersonReadOnly/PersonReadOnly.jsx
  src/pages/Dashboard/PlaceReadOnly/PlaceReadOnly.jsx
  src/pages/Dashboard/SearchOrganizations/SearchOrganizations.jsx
  src/pages/Dashboard/SearchPerson/SearchPerson.jsx
  src/pages/Dashboard/SearchPlaces/SearchPlaces.jsx
Labels: bug

#668 Bugfix/issue 667
  src/pages/Dashboard/OrganizationsReadOnly/OrganizationsReadOnly.jsx
  src/pages/Dashboard/PersonReadOnly/PersonReadOnly.jsx
  src/pages/Dashboard/PlaceReadOnly/PlaceReadOnly.jsx
Labels: bug

#670 fix: changed disambiguating description keyword to description for ar…
  src/components/Select/selectOption.settings.js
  src/components/TreeSelectOption/treeSelectOption.settings.js
Labels: bug

#671 Feature/issue 596
  src/pages/Dashboard/AddEvent/AddEvent.jsx
  src/pages/Dashboard/CreateNewOrganization/CreateNewOrganization.jsx
  src/pages/Dashboard/CreateNewPerson/CreateNewPerson.jsx
Labels: bug

#673 fix: appended my events to user filter in events
  src/pages/Dashboard/Events/Events.jsx
Labels: bug

#679 Bugfix/issue image crop 411
  src/components/ImageCrop/ImageCrop.jsx
  src/components/ImageUpload/ImageUpload.jsx
  src/pages/Dashboard/AddEvent/AddEvent.jsx
Labels: bug

#680 Bugfix/issue 664
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
Labels: bug

#685 Feature/tech support issue 28
  src/components/Modal/QuickCreatePlace/QuickCreatePlace.jsx
  src/components/Modal/QuickCreatePlace/quickCreatePlace.css
Labels: enhancement

#693 Bugfix/issue 582
  src/utils/bilingual.js
Labels: bug

#694 fix: changed the capitalization to none closes #30
  src/components/Tags/Common/tags.css
Labels: bug

#706 Develop
  .env.production
  src/pages/Dashboard/AddUser/AddUser.jsx
  src/pages/Dashboard/Settings/UserManagement/UserManagement.jsx
  src/pages/Dashboard/UserReadOnly/UserReadOnly.jsx
  src/services/invite.js
Labels: deployment

#707 fix: changed keyword original image url to original url in form fields
  src/constants/formFields.js
Labels: bug

#714 feat: added support for containsplace in edit and read only page
  src/components/List/SelectionItem/selectionItem.css
  src/locales/en/translationEn.json
  src/locales/fr/transalationFr.json
  src/pages/Dashboard/AddEvent/AddEvent.jsx
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
  src/pages/Dashboard/PlaceReadOnly/PlaceReadOnly.jsx
Labels: feature

#717 fix: changed feature key to ticket info .closes #711
  src/pages/Dashboard/EventReadOnly/EventReadOnly.jsx
Labels: bug

#732 Bugfix/issue 688
  src/constants/formFields.js
  src/pages/Dashboard/AddEvent/AddEvent.jsx
  src/pages/Dashboard/CreateNewPlace/CreateNewPlace.jsx
Labels: bug

#736 Feature/issue 677
  src/components/Modal/Common/customModal.css
  src/components/Modal/QuickCreateOrganization/QuickCreateOrganization.jsx
  src/components/Modal/QuickCreateOrganization/quickCreateOrganization.css
  src/components/Modal/QuickCreateSaving/QuickCreateSaving.jsx
  src/components/Modal/QuickCreateSaving/index.js
  src/components/Modal/QuickCreateSaving/quickCreateSaving.css
  src/locales/en/translationEn.json
  src/locales/fr/transalationFr.json
  src/pages/Dashboard/AddEvent/AddEvent.jsx
  src/pages/Dashboard/CreateNewOrganization/CreateNewOrganization.jsx
Labels: enhancement

#738 Bugfix/issue 576
  src/pages/Dashboard/AddEvent/AddEvent.jsx
Labels: bug

#737 Feature/issue 676
  src/components/List/SelectionItem/SelectionItem.jsx
  src/components/Select/selectOption.settings.js
  src/components/TreeSelectOption/treeSelectOption.settings.js
  src/constants/formFields.js
  src/pages/Dashboard/AddEvent/AddEvent.jsx
  src/pages/Dashboard/CreateNewOrganization/CreateNewOrganization.jsx
Labels: feature
